// <auto-generated />
using System;
using FitTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitTracker.Data.Migrations
{
    [DbContext(typeof(FitTrackerDbContext))]
    [Migration("20260705153442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitTracker.Core.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BodyWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("FitTracker.Core.Entities.ExerciseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("ExerciseSessions");
                });

            modelBuilder.Entity("FitTracker.Core.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("MealLogs");
                });

            modelBuilder.Entity("FitTracker.Core.Entities.ExerciseSession", b =>
                {
                    b.HasOne("FitTracker.Core.Entities.DailyLog", "DailyLog")
                        .WithMany("Exercises")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("FitTracker.Core.Entities.MealLog", b =>
                {
                    b.HasOne("FitTracker.Core.Entities.DailyLog", "DailyLog")
                        .WithMany("Meals")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("FitTracker.Core.Entities.DailyLog", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
